layout_spectrum: 0.5340425
color:
  saturation: 0.2340426
  lightness: 0.6638298
  brandStrength: 0.4148936
  rhythmicContrast: 0.6595744
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.1911053
name: Liza
